---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  labels:
      app: echo-server
spec:
  selector:
    matchLabels:
      app: echo-server
  replicas: 18
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
      - name: echo-server
        image: k8s.gcr.io/echoserver:1.10
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
  labels:
    app: echo-server
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: echo-server

# vi: ts=2 sts=2 sw=2 et :
